export const ActionTypes= {
	SET_PRODUCTS:'SET_PRODUCTS',
	SELECTED_PRODUCT: 'SELECTED_PRODUCT',
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	CHANGE_CART_QTY: 'CHANGE_CART_QTY',
	DECREMENT:'DECREMENT',
	INCREMENT:'INCREMENT'
}